owner: BinHexer
repo: lerncampus24-status

sites:
  - name: API
    url: https://api.lerncampus24.de/health
    expectedStatusCodes:
      - 200

  - name: Web App
    url: https://app.lerncampus24.de

  - name: Webseite
    url: https://lerncampus24.de

status-website:
  cname: status.lerncampus24.de
  logoUrl: https://lerncampus24.de/favicon.svg
  name: LernCampus24 Status
  introTitle: "Systemstatus"
  introMessage: "Echtzeit-Status aller LernCampus24 Dienste"
  theme: light

  navbar:
    - title: Startseite
      href: https://lerncampus24.de
    - title: Zur App
      href: https://app.lerncampus24.de

# German translations
i18n:
  activeIncidents: Aktuelle Störungen
  allSystemsOperational: Alle Systeme funktionieren einwandfrei
  incidentReport: "Störungsbericht für $DATE"
  pastIncidents: Vergangene Störungen
  ms: ms
  loading: Laden...
  navbarGitHub: GitHub
  incidentDetails: Störungsdetails
  incidentFixed: Behoben
  incidentOngoing: In Bearbeitung
  incidentScheduled: Geplant
  incidentCompleted: Abgeschlossen
  liveStatus: Live-Status
  overallUptime: "Verfügbarkeit: $UPTIME"
  averageResponseTime: "Durchschn. Antwortzeit: $TIME"
  day: Tag
  days: Tage
  hour: Stunde
  hours: Stunden
  minute: Minute
  minutes: Minuten
  second: Sekunde
  seconds: Sekunden
  degradedPerformance: Eingeschränkte Leistung
  completeOutage: Totalausfall
  partialOutage: Teilausfall

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  uptime: "*/5 * * * *"
